[pmat]
version = "2.213.11"
last_compliance_check = "2026-01-22T12:57:43.285967604Z"
auto_update = false

[exclude]
paths = [
    "book/book/**",
    "wasm-pkg/**",
    "crates/entrenar-wasm/pkg/**",
    "target/**",
]

[thresholds]
dead_code_percentage = 40.0
provability_score = 0.60
